CREATE TABLE Organisations (
  orgID INT NOT NULL AUTOINCREMENT,
  orgName TEXT NOT NULL,
  orgShort VARCHAR(3) NOT NULL,
  ownerID INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(orgID),
  FOREIGN KEY(ownerID) REFERENCES Users(userID)
);

CREATE TRIGGER [UpdateLastTime]
AFTER UPDATE
ON Organisations
FOR EACH ROW
BEGIN
UPDATE Organisations SET updated_at = CURRENT_TIMESTAMP WHERE orgID = old.orgID
END;
