CREATE TABLE Roles (
  roleID INT NOT NULL AUTOINCREMENT,
  organisation INT NOT NULL,
  roleName TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(roleID),
  FOREIGN KEY(organisation) REFERENCES Organisations(orgID)
);

CREATE TRIGGER [UpdateLastTime]
AFTER UPDATE
ON Roles
FOR EACH ROW
BEGIN
UPDATE Roles SET updated_at = CURRENT_TIMESTAMP WHERE roleID = old.roleID
END;
