CREATE TABLE Tasks (
  taskID INT NOT NULL,
  taskTitle TEXT NOT NULL,
  taskDescription TEXT NOT NULL,
  due_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(taskID)
);

CREATE TRIGGER [UpdateLastTime]
AFTER UPDATE
ON Tasks
FOR EACH ROW
BEGIN
UPDATE Tasks SET updated_at = CURRENT_TIMESTAMP WHERE taskID = old.taskID
END;
