CREATE TABLE Users (
  userID INT AUTOINCREMENT,
  pwdHash TEXT NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT 0,
  disabled BOOLEAN NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(userID)
);

CREATE TRIGGER [UpdateLastTime]
AFTER UPDATE
ON Users
FOR EACH ROW
BEGIN
UPDATE Users SET updated_at = CURRENT_TIMESTAMP WHERE userID = old.userID
END;

