CREATE TABLE UserOrgLink (
  userID INT NOT NULL,
  taskID INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(userID, taskID),
  FOREIGN KEY(userID) REFERENCES Users(userID),
  FOREIGN KEY(taskID) REFERENCES Tasks(taskID)
);
