CREATE TABLE UserRoleLink (
  userID INT NOT NULL,
  roleID INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(userID, roleID),
  FOREIGN KEY(userID) REFERENCES Users(userID),
  FOREIGN KEY(roleID) REFERENCES Roles(roleID)
);
